### 線形代数の基礎
線形代数は、ベクトルや行列などを扱う数学の分野の一つです。  
ディープラーニングでは、多くの数値を扱う必要があるのですが、線形代数を用いれば多くの数値に対する処理を簡潔な数式で記述することができます。

### スカラー
スカラー（scalar）は1、５、1.2、-7など通常の数値のこと。  
数式におけるアルファベット・ギリシャ文字の小文字はスカラー

In [1]:
# コード
a = 1
b = 1.2
c = -0.25
d = 1.2e5 # 1.2×10の5乗

### ベクトル
ベクトルは、スカラーを直線上に並べたものです。  
アルファベットの小文字に矢印を乗せたものでベクトルを表します。
$$ \begin{aligned}
\vec{a} & = \left(
    \begin{array}{c}
      1 \\
      2 \\
      3
    \end{array}
 \right) \\
 \vec{b} & = (-2.3, 0.25, -1.2, 1.8, 0.41) \\
 \vec{p} & = \left(
    \begin{array}{c}
      p_1 \\
      p_2 \\
      \vdots \\
      p_m
    \end{array}
 \right) \\
\vec{q} & = (q_1, q_2, \cdots, q_n)
\end{aligned} $$

縦ベクトルと横ベクトルがある。  
ベクトルはNumpyの1次元配列を用いて以下のように表せます。

In [2]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

b = np.array([-2.3, 0.25, -1.2, 1.8, 0.41])
print(b)

[1 2 3]
[-2.3   0.25 -1.2   1.8   0.41]


### 行列
行列はスカラーを格子状に並べたもの。
$$
   \left(
    \begin{array}{cccc}
      0.12 & -0.34 & 1.3 & 0.81 \\
      -1.4 & 0.25 & 0.69 & -0.41 \\
      0.25 & -1.5 & -0.15 & 1.1 \\
    \end{array}
  \right)
$$

なお、縦ベクトルは列の数が1の行列。  
横ベクトルは行の数が1の行列と考えることもできる。  
アルファベット大文字のイタリックで行列を表す。  
  
 $$
   A = \left(
    \begin{array}{cccc}
      0 & 1 & 2 \\
      3 & 4 & 5 \\
    \end{array}
  \right)
$$
$$
   P = \left(
    \begin{array}{cccc}
      p_{11} & p_{12} & \ldots & p_{1n} \\
      p_{21} & p_{22} & \ldots & p_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      p_{m1} & p_{m2} & \ldots & p_{mn} \\
    \end{array}
  \right) 
$$

行列$A$は2x3の行列で、行列$P$はm x nの行列です。  
また、$P$に見られるように、行列の要素を変数で表す際の添字の数は2つです。  

In [3]:
import numpy as np

a = np.array([[1, 2, 3],
                        [4, 5, 6]]) # 2×3の行列
print(a)
b = np.array([[0.21, 0.14],
                        [-1.3,  0.81],
                        [0.12, -2.1]])
print(b)

[[1 2 3]
 [4 5 6]]
[[ 0.21  0.14]
 [-1.3   0.81]
 [ 0.12 -2.1 ]]


### テンソル
テンソルはスカラーを複数の次元に並べたもので、スカラー、ベクトル、行列を含む。  
テンソルの概念（教材のコピペ）  
  
 <img src="../images/tensor.png"> 
 
 各要素につく添字の数をmそのテンソルの階数といいます。  
 スカラーには添字がないので0階のテンソル、ベクトルは添字が1つなので1階のテンソル、行列は添字が2つなので2階のテンソルなります。  
 より高次元なものは、3階のテンソル、4階のテンソル・・となります。
 
 Numpyの多次元配列を用いると、例えば次のように3階のテンソルを表現することができます。

In [4]:
import numpy as np

a = np.array([[[0, 1, 2, 3],
                          [2, 3, 4, 5],
                          [4, 5, 6, 7]],
             
                        [[1, 2, 3, 4],
                          [3, 4, 5, 6],
                          [5, 6, 7, 8]]]) # (2, 3, 4)の3階のテンソル
print(a)

[[[0 1 2 3]
  [2 3 4 5]
  [4 5 6 7]]

 [[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]


このコードにおけるaは3階のテンソルです。  
Numpyを利用すれば、さらに高次元の配列を表現することができます。(でも書きにくいなー感)

### 行列積
行列積では、前の行列における行の各要素と、後ろの行列における列の各要素を掛け合わせて総和をとり、新しい行列の要素とする。  
左の行列の全ての行と、右の行列の全ての列の組み合わせで演算を行、新たな行列を作ります。行列積の例をみてみましょう（教材のコピー）  

まず、行列$A$と$B$を次のように設定します。  

$$
   A = \left(
    \begin{array}{ccc}
      a_{11} & a_{12} & a_{13} \\
      a_{21} & a_{22} & a_{23} \\
    \end{array}
  \right)
$$ 

$$ 
   B = \left(
    \begin{array}{cc}
      b_{11} & b_{12} \\
      b_{21} & b_{22} \\
      b_{31} & b_{32} \\
    \end{array}
  \right)
$$ 

$A$は2x3の行列で、$B$は3x2の行列です。  
そして、$A$と$B$の積を次のように表します。  

$$ 
   AB = \left(
    \begin{array}{ccc}
      a_{11} & a_{12} & a_{13} \\
      a_{21} & a_{22} & a_{23} \\
    \end{array}
  \right) 
  \left(
    \begin{array}{cc}
      b_{11} & b_{12} \\
      b_{21} & b_{22} \\
      b_{31} & b_{32} \\
    \end{array}
  \right) \\
 = \left(
    \begin{array}{ccc}
      a_{11}b_{11}+a_{12}b_{21}+a_{13}b_{31} & a_{11}b_{12}+a_{12}b_{22}+a_{13}b_{32} \\
      a_{21}b_{11}+a_{22}b_{21}+a_{23}b_{31} & a_{21}b_{12}+a_{22}b_{22}+a_{23}b_{32} \\
    \end{array}
  \right) \\
 = \left(
    \begin{array}{ccc}
      \sum\limits_{k=1}^3 a_{1k}b_{k1} & \sum\limits_{k=1}^3 a_{1k}b_{k2} \\
      \sum\limits_{k=1}^3 a_{2k}b_{k1} & \sum\limits_{k=1}^3 a_{2k}b_{k2} \\
    \end{array}
  \right)
$$ 

$A$の各行と$B$の各列の各要素を掛け合わせて総和をとり、新しい行列の各要素とします。  
上記の行列積には総和の記号$\Sigma$が登場していますが、行列積は積の総和を計算する際に大活躍します。  
人工知能では積の総和を頻繁に計算するので、行列積は欠くことができません。 

スカラーの積と異なり、行列積においては、前の行列と後ろの行列の交換は特定の条件を除きできません。  
そして、行列積を計算するには、**前の行列の列数と、後ろの行列の行数が一致していなければいけません**  
例えば、前の行列の列数が3であれば、後ろの行列の行数は3である必要があります。

In [3]:
# コードでかくと
import numpy as np
 
a = np.array([[0, 1, 2],
                         [1, 2, 3]])
b = np.array([[2, 1],
                         [2, 1],
                         [2, 1]])
print(np.dot(a, b))

[[ 6  3]
 [12  6]]


### 要素ごとの積（アダマール積）

行列の要素ごとの積は、アダマール積とも呼ばれており、行列の各要素を掛け合わせます。  
以下の行列$A$、$B$を考えましょう。

$$  \begin{aligned} \\
   A & = \left(
    \begin{array}{cccc}
      a_{11} & a_{12} & \ldots & a_{1n} \\
      a_{21} & a_{22} & \ldots & a_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      a_{m1} & a_{m2} & \ldots & a_{mn}
    \end{array}
  \right) \\
   B & = \left(
    \begin{array}{cccc}
      b_{11} & b_{12} & \ldots & b_{1n} \\
      b_{21} & b_{22} & \ldots & b_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      b_{m1} & b_{m2} & \ldots & b_{mn}
    \end{array}
  \right)
\end{aligned} $$ 

これらの行列の要素ごとの積は、演算子$\circ$を用いて次のように表すことができます。

$$
   A\circ B = \left(
    \begin{array}{cccc}
      a_{11}b_{11} & a_{12}b_{12} & \ldots & a_{1n}b_{1n} \\
      a_{21}b_{21} & a_{22}b_{22} & \ldots & a_{2n}b_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      a_{m1}b_{m1} & a_{m2}b_{m2} & \ldots & a_{mn}b_{mn}
    \end{array}
  \right)
$$


In [4]:
# コードで書くと
import numpy as np

a = np.array([[0, 1, 2],
                        [3, 4, 5],
                        [6, 7 , 8]])
b = np.array([[0, 1, 2],
                        [2, 0, 1],
                        [1, 2, 0]])

print(a*b)

[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


要素ごとの積をけいさんするためには、配列の形状が同じである必要があります。  
要素ごとの和には+,要素ごとの差には-,要素ごとの割り算には/を使います

### 転置
行列を転置することにより、行と列が入れ替わります。  
例えば行列$A$の転置行列は$A^{\mathrm{T}}$と表します。  


$$  \begin{aligned} \\
   A & = \left(
    \begin{array}{ccc}
      1 & 2 & 3 \\
      4 & 5 & 6 \\
    \end{array}
  \right) \\
   A^{\mathrm{T}} & = \left(
    \begin{array}{cc}
      1 & 4 \\
      2 & 5 \\
      3 & 6 \\
    \end{array}
  \right) \\
\end{aligned} $$ 

$$  \begin{aligned} \\
   B & = \left(
    \begin{array}{cc}
      a & b \\
      c & d \\
      e & f \\
    \end{array}
  \right) \\
   B^{\mathrm{T}} & = \left(
    \begin{array}{ccc}
      a & c & e \\
      b & d & f \\
    \end{array}
  \right) \\
\end{aligned} $$ 

In [5]:
#コードにすると（すごく簡単）
import numpy as np

a = np.array([[1,2,3],
                        [4,5,6]])
print(a.T)

[[1 4]
 [2 5]
 [3 6]]
